### PR TITLE
Add convection tuning parameters to namelist

### PR DESCRIPTION
**Pull request by lisa-bengtsson**
Add convection tuning parameters to namelist, default values are for SAS in HR prototypes 1 through 3.

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@lisa-bengtsson should this coincide with a model update as well?

**Comment by lisa-bengtsson** [comment]
Yes, do I update this in the checkout script? e.g. point to a new hash?

**Comment by JessicaMeixner-NOAA** [comment]
Yes, but we'll have to  wait until the PR is merged to get that new hash.

**Comment by lisa-bengtsson** [comment]
ok, yes, I will keep an eye out for the new hash and then update this PR - hang tight!

**Comment by JessicaMeixner-NOAA** [comment]
@lisa-bengtsson sounds good!  In the meantime I looked at the PR and I don't think there are other updates to make from that PR - but thought I'd double check.  All the other updates to the input shouldn't need updated here to my understanding.

**Comment by lisa-bengtsson** [comment]
That is my understanding as well. The ones pertaining to gravity wave drag are for a different application. Only these 3 parameters in this PR concern HR3.

**Comment by JessicaMeixner-NOAA** [comment]
@lisa-bengtsson I merged this in and will update the model hash, run a quick test and submit the PR!

**Comment by lisa-bengtsson** [comment]
Thank you!

**Pull request merged**
